#pragma once

enum rocksdbErrorCode
{
    ROCKSDB_ERROR_BEGIN = 500,
    ROCKSDB_OPEN_ERROR = 501,
    ROCKSDB_PUT_ERROR = 502,
    ROCKSDB_GET_ERROR = 503,
    ROCKSDB_DELETE_ERROR = 504,
    ROCKSDB_DELETE_RANGE_ERROR = 505,
};