#pragma once

enum rocksdbErrorCode
{
    ROCKSDB_ERROR_BEGIN = 500,
    ROCKSDB_OPEN_ERROR,
    ROCKSDB_PUT_ERROR,
    ROCKSDB_WRITE_ERROR,
    ROCKSDB_GET_ERROR,
    ROCKSDB_DELETE_ERROR,
    ROCKSDB_DELETE_RANGE_ERROR,
    ROCKSDB_CLOSE_ERROR,
    ROCKSDB_DESTROY_ERROR,
    ROCKSDB_BATCH_DELETE_ERROR,
    ROCKSDB_COMMIT_ERROR,
};